trunk/taskprogect/config/routes.rb
Taskprogect::Application.routes.draw do

  resources :projects
  resources :tasks do
    collection do
      get :completed
    end
    member do
      put :markcomplete
    end
  end

  root :to => "projects#index"

  match "task_archive", :to => "tasks#archive"
  

end

trunk/taskprogect/app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :tasks
  
end

trunk/taskprogect/app/models/task.rb
class Task < ActiveRecord::Base
  
  belongs_to :project, :counter_cache => true

  validates :name, :length => { :minimum => 3 }
  
#   def validate
#     errors.add(:mane, "Name is invalid")
#   end
  
  def self.find_incomplete(options={})
    with_scope :find => options do
      find_all_by_complete(false, :order => "name DESC")
    end
  end
  
#     def self.find_incomplete(options={})
#     
#       find_all_by_complete(false, options.merge(:order => "name DESC"))
#     
#   end
  
end

trunk/taskprogect/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

trunk/taskprogect/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  layout :user_layout
  
  def index
    @projects = Project.find(:all)
    render :layout => "projects"
  end
  
  private
  
  def user_layout
    if false
      "admin"
    else
      "application"
    end
  end
  
end

trunk/taskprogect/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      redirect_to task_path(@task)
      flash[:notice] = "Task created"
    else
      render("new")
      flash[:notice] = "Task not created"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to task_path(@task)
    else
      render("edit")
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Task destroyed."
    redirect_to tasks_path
  end

  def archive
    @tasks = Task.where(:complete => params[:comp])
  end

  def markcomplete
    @task = Task.find(params[:id])
    @task.update_attribute(:complete, true)
    flash[:notice] = "Task complete updated"
    redirect_to completed_tasks_path
  end

  def completed
    @tasks = Task.where(:complete => true)
  end
  
end

trunk/taskprogect/app/helpers/application_helper.rb
module ApplicationHelper
end

trunk/taskprogect/app/helpers/progects_helper.rb
module ProgectsHelper
end

trunk/taskprogect/app/helpers/projects_helper.rb
module ProjectsHelper
end

trunk/taskprogect/app/helpers/tasks_helper.rb
module TasksHelper
end

trunk/taskprogect/app/views/layouts/admin.html.erb
<h1>Admin layout!</h1>
<%= yield %>

trunk/taskprogect/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskprogect</title>
  <h1>Application layout!</h1>
  <%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>

</head>
<body>






<%= yield %>

</body>
</html>

trunk/taskprogect/app/views/layouts/projects.html.erb
<h1>Projects layout!</h1>
<%= yield %>

trunk/taskprogect/app/views/projects/index.html.erb
<h2>Projects</h2>
  <%= link_to "Tasks", tasks_path %>
<ul>
<% for project in @projects %>
<li><%= project.name%> (<%= pluralize project.tasks.size, 'task' %>)</li>
<% end %>
</ul>
<%= link_to "archive", task_archive_path(:comp => 1) %>
<%= task_archive_path %>

trunk/taskprogect/app/views/shared/_error_messages.html.erb
    <% if target.errors.any? %>
   <div id="errorExplanation">
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
   <ul>
   <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
  <% end %>
   </ul>
  </div>
  <% end %>

trunk/taskprogect/app/views/tasks/_form.html.erb
    <%= render "shared/error_messages", :target => @task %>
    <%= f.label :name %>
    <%= f.text_field :name  %> </br>
    <%= f.label :complete %>
    <%= f.select(:complete, [["ne complete", false], ["complete", true]]) %> </br>
    <%= f.label "project_id" %>
    <%= f.select(:project_id, Project.all.collect{|p| [p.name, p.id]}) %> </br>

trunk/taskprogect/app/views/tasks/archive.html.erb
<%= @tasks.inspect %>

trunk/taskprogect/app/views/tasks/completed.html.erb
<%= link_to "Tasks", tasks_path %>
<p><h1>Completed tasks at tasks:completed</h1></p>

<p>Name | created_at | project_id</p>
<% for task in @tasks %>

<p><%= task.name%>
<%= task.created_at.to_s(:due_time) %>
  | <%= task.project_id %> |
   <%= task.complete %>
  <%= link_to "Show", task_path(task) %>
  <%= link_to "Edit", edit_task_path(task) %>
  <%= button_to "Destroy", task, :method => :delete, :confirm => "Are you sure?" %>
  <%= link_to "Delete", task, :method => :delete, :confirm => "Are you sure?", :title => "Delete #{task.name}" %>



</p>
<% end %>

trunk/taskprogect/app/views/tasks/edit.html.erb
<%= link_to "<< Back to list tasks", tasks_path %>


    <%= form_for(@task) do |f| %>
    <%= render "form", :f => f %>

     <%= submit_tag "update task" %>
<% end %>

trunk/taskprogect/app/views/tasks/index.html.erb
<%= flash[:notice] %>

<p><%= link_to "Projects", projects_path %> | <%= link_to "completed tasks", completed_tasks_path %></p>

<p>Name | created_at | project_id</p>
<% for task in @tasks %>

<p><%= task.name%>
<%= task.created_at.to_s(:due_time) %>
  | <%= task.project_id %> |
   <%= task.complete %>
  <%= link_to "Show", task_path(task) %>
  <%= link_to "Edit", edit_task_path(task) %>
  <%= button_to "Destroy", task, :method => :delete, :confirm => "Are you sure?" %>
  <%= link_to "Delete", task, :method => :delete, :confirm => "Are you sure?", :title => "Delete #{task.name}" %>
  <%= (link_to "Mark as complete", markcomplete_task_path(task), :method => :put) if !task.complete? %>



</p>
<% end %>

<%= link_to "Create new task", new_task_path %>

trunk/taskprogect/app/views/tasks/new.html.erb
<%= link_to "<< Back to list tasks", tasks_path %>


    <%= form_for(@task, new_task_path ) do |f| %>
    <%= render "form", :f => f %>

     <%= submit_tag "create new task" %>
<% end %>

<%= @projects.inspect %>
<%= new_task_path.inspect %>

trunk/taskprogect/app/views/tasks/show.html.erb
<%= link_to "Back to list", tasks_path %>
<p><%= @task.name %></p>
<p><%= @task.complete %></p>
<p><%= @task.project_id %></p>